-- MySQL Script generated by MySQL Workbench
-- Fri Nov 30 08:51:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema restaurante
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurante` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema super
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `idcategorias` INT NOT NULL,
  `nombre_categorias` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(45) NULL,
  `Stock` INT NULL,
  `idcategorias` INT NULL,
  `categorias_idcategorias` INT NOT NULL,
  PRIMARY KEY (`idProducto`, `categorias_idcategorias`),
  INDEX `fk_producto_categorias1_idx` (`categorias_idcategorias` ASC) VISIBLE,
  CONSTRAINT `fk_producto_categorias1`
    FOREIGN KEY (`categorias_idcategorias`)
    REFERENCES `mydb`.`categorias` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `restaurante` ;

-- -----------------------------------------------------
-- Table `restaurante`.`platos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`platos` (
  `plato_id` INT(11) NOT NULL AUTO_INCREMENT,
  `plato_nombre` VARCHAR(45) NULL DEFAULT NULL,
  `plato_calorias` INT(11) NULL DEFAULT NULL,
  `plato_cuchara` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`plato_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante`.`ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`ingredientes` (
  `plato_id` INT(11) NOT NULL,
  `ingrediente_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`plato_id`, `ingrediente_nombre`),
  INDEX `ing_fk_platos` (`plato_id` ASC) VISIBLE,
  CONSTRAINT `ing_fk_platos`
    FOREIGN KEY (`plato_id`)
    REFERENCES `restaurante`.`platos` (`plato_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`menus` (
  `menu_id` INT(11) NOT NULL AUTO_INCREMENT,
  `menu_nombre` VARCHAR(45) NULL DEFAULT NULL,
  `menu_precio` DECIMAL(2,0) NULL DEFAULT NULL,
  PRIMARY KEY (`menu_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante`.`menus_platos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`menus_platos` (
  `mp_tipo` VARCHAR(10) NULL DEFAULT NULL,
  `plato_id` INT(11) NOT NULL,
  `menu_id` INT(11) NOT NULL,
  PRIMARY KEY (`plato_id`, `menu_id`),
  INDEX `mp_fk_platos` (`plato_id` ASC) VISIBLE,
  INDEX `mp_fk_menus` (`menu_id` ASC) VISIBLE,
  CONSTRAINT `mp_fk_menus`
    FOREIGN KEY (`menu_id`)
    REFERENCES `restaurante`.`menus` (`menu_id`),
  CONSTRAINT `mp_fk_platos`
    FOREIGN KEY (`plato_id`)
    REFERENCES `restaurante`.`platos` (`plato_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
